# Generated by Django 4.2.5 on 2023-09-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages='User with this email is already exist', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
