# Generated by Django 4.2.5 on 2023-09-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'User with this email is already exist'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
